[package]
name = "kafka-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = {version = "0.37.0",features = ["cmake-build"]}
tokio = {version = "1.36.0", features = ["full"]}
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
futures = "0.3"
